In [1]:
pip install --upgrade pip

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai

## Introduction numpy
## Introduction pandas


In [2]:
L = [1, 2, 3]
L > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [3]:
import numpy as np

In [4]:
L_array = np.array(L)

In [5]:
L_array > 2

array([False, False,  True])

In [6]:
# number of dimensions
L_array.ndim

1

In [7]:
# size
L_array.size

3

In [11]:
L2 = np.arange(9)
L3 = L2.reshape((3,3))


In [12]:
L3.ndim

2

In [13]:
L3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Slicing, indexing
#### Indexing

In [16]:
L2[4]

np.int64(4)

In [18]:
L2[-1]

np.int64(8)

In [17]:
L2[:4]

array([0, 1, 2, 3])

In [19]:
L2[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
L2[:-2]

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
L2[6:]

array([6, 7, 8])

In [23]:
L2[L2 > 5]

array([6, 7, 8])

In [ ]:
#### Generate vectors

In [42]:
np.random.seed(0)
age = np.random.normal(60, 10, 20).round().astype(int)
age

array([78, 64, 70, 82, 79, 50, 70, 58, 59, 64, 61, 75, 68, 61, 64, 63, 75,
       58, 63, 51])

In [43]:
## simulate gender
np.random.seed(0)
gender = np.random.choice(["Male", "Female"], 20, p=[0.4, 0.6])
gender

array(['Female', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female'],
      dtype='<U6')

In [44]:
len(gender[gender == "Female"])

16

In [49]:
print(np.sum(gender == "Female"))

16


In [54]:
np.linspace(6, 8, 25).round(2)

array([6.  , 6.08, 6.17, 6.25, 6.33, 6.42, 6.5 , 6.58, 6.67, 6.75, 6.83,
       6.92, 7.  , 7.08, 7.17, 7.25, 7.33, 7.42, 7.5 , 7.58, 7.67, 7.75,
       7.83, 7.92, 8.  ])

In [14]:
L3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Introduction to pandas

In [55]:
import pandas as pd

In [66]:
pd.DataFrame(np.array([age, gender]).T,
             columns = ['Age', 'Gender'])

Age  Gender
0   78  Female
1   64  Female
2   70  Female
3   82  Female
4   79  Female
5   50  Female
6   70  Female
7   58  Female
8   59  Female
9   64    Male
10  61  Female
11  75  Female
12  68  Female
13  61  Female
14  64    Male
15  63    Male
16  75    Male
17  58  Female
18  63  Female
19  51  Female

In [58]:
my_dict = {
    "Age": age,
    "Gender": gender
}

data_sim = pd.DataFrame(my_dict)

In [59]:
data_sim.head()

Age  Gender
0   78  Female
1   64  Female
2   70  Female
3   82  Female
4   79  Female

In [74]:
data_sim['Gender'].value_counts() #.plot(kind="pie")

Gender
Female    16
Male       4
Name: count, dtype: int64

In [71]:
data_sim.groupby(['Gender'])['Age'].mean()#.plot(kind="pie")

Gender
Female    65.4375
Male      66.5000
Name: Age, dtype: float64

In [75]:
# subset of under 60
data_sim[data_sim['Age'] < 60]

# Add a new column of marital status using np.random.choice

Age  Gender
5    50  Female
7    58  Female
8    59  Female
17   58  Female
19   51  Female

```python
df['new_col'] = value
```

In [77]:
np.random.seed(1)
data_sim['Marital'] = np.random.choice(['Single', 'Married', 'Divorced'], 20)

In [78]:
data_sim.head()

Age  Gender  Marital
0   78  Female  Married
1   64  Female   Single
2   70  Female   Single
3   82  Female  Married
4   79  Female  Married

In [80]:
pd.crosstab(data_sim['Gender'], data_sim['Marital'])

Marital  Divorced  Married  Single
Gender                            
Female          3        5       8
Male            1        2       1